name: Push to Github Registry
concurrency: 
  group: docker-image-${{ github.ref }}
  cancel-in-progress: true
on:
  repository_dispatch:
    types: [update-image]
  push:
    branches:
      - master
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ github.token }}
          image-name: docker-action-runner
          dockerfile: Dockerfile
          custom-args: --platform=linux/arm64,linux/amd64
